on: pull_request
name: Git checks
jobs:
  check-branch-name:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check branch name respects naming conventions
        id: branchnamecheck
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking branch name..."
          ALLOWED_PREFIXES="feature feat fix hotfix release chore dependabot docs test refactor style ci"
          BRANCH_NAME_VALID=false
          PREFIXES_ARRAY=$(echo $ALLOWED_PREFIXES | tr " " "\n")
          for PREFIX in $PREFIXES_ARRAY ; 
          do 
          if [[ "${{ github.head_ref }}" == $PREFIX/* ]]; then
              echo "${{ github.head_ref }} respects prefix $PREFIX"
              BRANCH_NAME_VALID=true
          else
              echo "${{ github.head_ref }} DOES NOT respects prefix $PREFIX"
          fi
          done
          if [[ $BRANCH_NAME_VALID == true ]]; then
              echo "[SUCCESS] - Your branch name respect the naming convention"  
          else
              echo "[FAIL] - Branch ${{ github.head_ref }} does not respect the naming convention, please rename"  
              exit 1
          fi
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title respects naming conventions
        id: checkprtitle
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking PR title..."
          ALLOWED_PREFIXES="feat fix docs style refactor test chore ci"
          PREFIXES_ARRAY=$(echo $ALLOWED_PREFIXES | tr " " "\n")
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_TITLE_VALID=false
          for PREFIX in $PREFIXES_ARRAY ; 
          do 
            if [[ "$PR_TITLE" == $PREFIX\(*\):\ * ]]; then
                PR_TITLE_VALID=true
                echo "$PR_TITLE respects prefix $PREFIX"
            else
                echo "$PR_TITLE DOES NOT respects prefix $PREFIX"
            fi
          done
          if [[ $PR_TITLE_VALID == true ]]; then
              echo "[SUCCESS] - Your PR title respects the naming convention"  
          else
              echo "[FAIL] - Your PR title does not respect the naming convention, please rename"  
              exit 1
          fi
  up-to-date:
    name: Check branch up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check up to date
        id: checkuptodate
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main checking if branch is up to date..."
          count=$(git rev-list --count origin/${{ github.head_ref }}..origin/${{ github.base_ref }})
          if [ $count == 0 ]; then
            echo "[SUCCESS] - Your branch is up to date"  
          else
            echo "[FAIL] - your branch is $count commits late. Please rebase."  
            exit 1
          fi 
